// api/_data/reference/copilot.ts
import type { ReferenceSection } from "../types";

export const copilotReference: ReferenceSection = {
  id: "copilot",
  title: "Copilot",
  description: "AI-powered workflow builder. Describe what you want in natural language and the copilot generates the workflow graph.",
  introduction: "The Copilot API provides an AI-assisted workflow builder. Create a copilot session linked to a workflow, describe what you want in natural language, and the copilot generates the workflow graph. You can iterate through multiple chat turns to refine the workflow, then save a snapshot to apply the generated graph.",
  commonPatterns: "Create a copilot session with a workflow_id, send messages via the chat endpoint (streaming SSE), and save good suggestions with the snapshot endpoint. Each chat message can produce a new version of the workflow graph. The copilot maintains conversation context within a session.",
  groups: [
    {
      endpoints: [
        { method: "POST", path: "/api/copilot/sessions", description: "Create a copilot session for a workflow.", requestBody: `{ "workflow_id": "wf-uuid" }`, snippets: { python: `requests.post(f"{BASE_URL}/api/copilot/sessions", headers=headers, json={"workflow_id": wf_id})`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/sessions\`, { method: "POST", headers, body: JSON.stringify({ workflow_id: wfId }) });`, curl: `curl -X POST '{BASE_URL}/api/copilot/sessions' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}" -H "Content-Type: application/json" -d '{"workflow_id": "uuid"}'` } },
        { method: "GET", path: "/api/copilot/sessions", description: "Get session by workflow_id.", parameters: [{ name: "workflow_id", in: "query", type: "string", required: true, description: "Workflow ID" }], snippets: { python: `requests.get(f"{BASE_URL}/api/copilot/sessions?workflow_id={wf_id}", headers=headers)`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/sessions?workflow_id=\${wfId}\`, { headers });`, curl: `curl '{BASE_URL}/api/copilot/sessions?workflow_id={wf_id}' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}"` } },
        { method: "DELETE", path: "/api/copilot/sessions/{id}", description: "Delete a copilot session.", parameters: [{ name: "id", in: "path", type: "string", required: true, description: "Session ID" }], snippets: { python: `requests.delete(f"{BASE_URL}/api/copilot/sessions/{session_id}", headers=headers)`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/sessions/\${sessionId}\`, { method: "DELETE", headers });`, curl: `curl -X DELETE '{BASE_URL}/api/copilot/sessions/{id}' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}"` } },
        { method: "GET", path: "/api/copilot/sessions/{id}/messages", description: "Get copilot conversation history.", parameters: [{ name: "id", in: "path", type: "string", required: true, description: "Session ID" }], snippets: { python: `requests.get(f"{BASE_URL}/api/copilot/sessions/{session_id}/messages", headers=headers)`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/sessions/\${sessionId}/messages\`, { headers });`, curl: `curl '{BASE_URL}/api/copilot/sessions/{id}/messages' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}"` } },
        { method: "POST", path: "/api/copilot/sessions/{id}/messages/{mid}/snapshot", description: "Save the copilot's workflow suggestion as a snapshot.", parameters: [{ name: "id", in: "path", type: "string", required: true, description: "Session ID" }, { name: "mid", in: "path", type: "string", required: true, description: "Message ID" }], snippets: { python: `requests.post(f"{BASE_URL}/api/copilot/sessions/{session_id}/messages/{message_id}/snapshot", headers=headers)`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/sessions/\${sessionId}/messages/\${messageId}/snapshot\`, { method: "POST", headers });`, curl: `curl -X POST '{BASE_URL}/api/copilot/sessions/{id}/messages/{mid}/snapshot' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}"` } },
        { method: "POST", path: "/api/copilot/sessions/{id}/chat", description: "Send a message and stream the copilot response (SSE).", parameters: [{ name: "id", in: "path", type: "string", required: true, description: "Session ID" }], requestBody: `{ "message": "Build a workflow that..." }`, snippets: { python: `requests.post(f"{BASE_URL}/api/copilot/sessions/{session_id}/chat", headers=headers, json={"message": "Build a workflow that..."}, stream=True)`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/sessions/\${sessionId}/chat\`, { method: "POST", headers, body: JSON.stringify({ message: "Build a workflow that..." }) });`, curl: `curl -N -X POST '{BASE_URL}/api/copilot/sessions/{id}/chat' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}" -H "Content-Type: application/json" -d '{"message": "Build a workflow that..."}'` } },
        { method: "GET", path: "/api/copilot/settings/model", description: "Get copilot model configuration.", snippets: { python: `requests.get(f"{BASE_URL}/api/copilot/settings/model", headers=headers)`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/settings/model\`, { headers });`, curl: `curl '{BASE_URL}/api/copilot/settings/model' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}"` } },
        { method: "PUT", path: "/api/copilot/settings/model", description: "Set copilot model.", requestBody: `{ "model": "gpt-4o" }`, snippets: { python: `requests.put(f"{BASE_URL}/api/copilot/settings/model", headers=headers, json={"model": "gpt-4o"})`, typescript: `await fetch(\`\${BASE_URL}/api/copilot/settings/model\`, { method: "PUT", headers, body: JSON.stringify({ model: "gpt-4o" }) });`, curl: `curl -X PUT '{BASE_URL}/api/copilot/settings/model' -H "apikey: {API_KEY}" -H "Authorization: Bearer {API_KEY}" -H "Content-Type: application/json" -d '{"model": "gpt-4o"}'` } },
      ],
    },
  ],
  errorResponses: [
    { status: 404, code: "session_not_found", description: "No copilot session exists with the given ID" },
  ],
};
